/**
 * test-data.js
 * Contains sample state variables for automated testing.
 */

// state data for Review.test.js
var testSurveyFormState1 = {
  surveyData: {
    beachID: null,
    beachName: "Boardwalk Beach (test)",
    cleanUpDate: "2020-03-23",
    cleanUpTime: "10:30",
    compassDegrees: "180",
    email: "stgibson@ucsc.edu",
    latDeg: "36",
    latDir: "1",
    latMin: "57",
    latSec: "12",
    locationChoiceDebris: true,
    lonDeg: "122",
    lonDir: "-1",
    lonMin: "2",
    lonSec: "28",
    microFreshTotalRib1: "0",
    microFreshTotalRib2: "0",
    microFreshTotalRib3: "0",
    microFreshTotalRib4: "0",
    microWeatheredTotalRib1: "0",
    microWeatheredTotalRib2: "0",
    microWeatheredTotalRib3: "0",
    microWeatheredTotalRib4: "0",
    orgLoc: "Santa Cruz, United States of America",
    orgName: "Clean Oceans International",
    rib1End: "50",
    rib1Start: "5",
    rib2End: "50",
    rib2Start: "10",
    rib3End: "50",
    rib3Start: "16",
    rib4End: "50",
    rib4Start: "27",
    riverDistance: "10",
    riverName: "Kawa Rivera",
    slope: "winter",
    substrateTypeSand: true,
    tideHeightA: "10",
    tideHeightB: "10",
    tideTimeA: "16:00",
    tideTimeB: "12:00",
    tideTypeA: "high",
    tideTypeB: "low",
    usageRecreation: true,
    userFirst: "Sean",
    userLast: "Gibson",
    windDir: "s",
    windSpeed: "10"
  },
  SRSData: {
    cigaretteButts__fresh__1: "5",
    cigaretteButts__fresh__2: "6",
    cigaretteButts__fresh__3: "4",
    cigaretteButts__fresh__4: "5",
    cigaretteButts__weathered__1: "3",
    cigaretteButts__weathered__2: "0",
    cigaretteButts__weathered__3: "3",
    cigaretteButts__weathered__4: "3",
    fishingLineRope__fresh__1: "1",
    fishingLineRope__fresh__2: "2",
    fishingLineRope__fresh__3: "4",
    fishingLineRope__fresh__4: "3",
    fishingLineRope__weathered__1: "3",
    fishingLineRope__weathered__2: "4",
    fishingLineRope__weathered__3: "0",
    fishingLineRope__weathered__4: "0",
    plasticCups__fresh__1: "2",
    plasticCups__fresh__2: "2",
    plasticCups__fresh__3: "2",
    plasticCups__fresh__4: "2",
    plasticCups__weathered__1: "3",
    plasticCups__weathered__2: "3",
    plasticCups__weathered__3: "3",
    plasticCups__weathered__4: "3",
    plasticStraws__fresh__1: "0",
    plasticStraws__fresh__2: "0",
    plasticStraws__fresh__3: "1",
    plasticStraws__fresh__4: "3",
    plasticStraws__weathered__1: "1",
    plasticStraws__weathered__2: "6",
    plasticStraws__weathered__3: "3",
    plasticStraws__weathered__4: "2",
    filmedPlastic__fresh__1: "0",
    filmedPlastic__fresh__2: "0",
    filmedPlastic__fresh__3: "0",
    filmedPlastic__fresh__4: "0",
    filmedPlastic__weathered__1: "0",
    filmedPlastic__weathered__2: "0",
    filmedPlastic__weathered__3: "0",
    filmedPlastic__weathered__4: "0",
    miscPlastic__fresh__1: "2",
    miscPlastic__fresh__2: "1",
    miscPlastic__fresh__3: "1",
    miscPlastic__fresh__4: "2",
    miscPlastic__weathered__1: "1",
    miscPlastic__weathered__2: "1",
    miscPlastic__weathered__3: "0",
    miscPlastic__weathered__4: "1",
    plasticBottlesCaps__fresh__1: "1",
    plasticBottlesCaps__fresh__2: "1",
    plasticBottlesCaps__fresh__3: "1",
    plasticBottlesCaps__fresh__4: "0",
    plasticBottlesCaps__weathered__1: "2",
    plasticBottlesCaps__weathered__2: "4",
    plasticBottlesCaps__weathered__3: "3",
    plasticBottlesCaps__weathered__4: "1",
    styrofoam__fresh__1: "1",
    styrofoam__fresh__2: "1",
    styrofoam__fresh__3: "0",
    styrofoam__fresh__4: "0",
    styrofoam__weathered__1: "0",
    styrofoam__weathered__2: "0",
    styrofoam__weathered__3: "1",
    styrofoam__weathered__4: "1",
    foodOrganic__fresh__1: "2",
    foodOrganic__fresh__2: "0",
    foodOrganic__fresh__3: "1",
    foodOrganic__fresh__4: "2",
    foodOrganic__weathered__1: "1",
    foodOrganic__weathered__2: "0",
    foodOrganic__weathered__3: "0",
    foodOrganic__weathered__4: "0",
    urethaneFoam__fresh__1: "0",
    urethaneFoam__fresh__2: "0",
    urethaneFoam__fresh__3: "1",
    urethaneFoam__fresh__4: "1",
    urethaneFoam__weathered__1: "1",
    urethaneFoam__weathered__2: "1",
    urethaneFoam__weathered__3: "0",
    urethaneFoam__weathered__4: "0",
    metal__fresh__1: "0",
    metal__fresh__2: "0",
    metal__fresh__3: "0",
    metal__fresh__4: "0",
    metal__weathered__1: "0",
    metal__weathered__2: "0",
    metal__weathered__3: "1",
    metal__weathered__4: "0",
    glass__fresh__1: "1",
    glass__fresh__2: "1",
    glass__fresh__3: "0",
    glass__fresh__4: "0",
    glass__weathered__1: "0",
    glass__weathered__2: "0",
    glass__weathered__3: "0",
    glass__weathered__4: "0",
    cottonCloth__fresh__1: "1",
    cottonCloth__fresh__2: "1",
    cottonCloth__fresh__3: "0",
    cottonCloth__fresh__4: "2",
    cottonCloth__weathered__1: "2",
    cottonCloth__weathered__2: "2",
    cottonCloth__weathered__3: "4",
    cottonCloth__weathered__4: "0",
    aluminumCans__fresh__1: "1",
    aluminumCans__fresh__2: "0",
    aluminumCans__fresh__3: "0",
    aluminumCans__fresh__4: "1",
    aluminumCans__weathered__1: "0",
    aluminumCans__weathered__2: "0",
    aluminumCans__weathered__3: "0",
    aluminumCans__weathered__4: "1",
    hygieneItems__fresh__1: "0",
    hygieneItems__fresh__2: "0",
    hygieneItems__fresh__3: "0",
    hygieneItems__fresh__4: "1",
    hygieneItems__weathered__1: "0",
    hygieneItems__weathered__2: "0",
    hygieneItems__weathered__3: "0",
    hygieneItems__weathered__4: "1",
    tileBrick__fresh__1: "0",
    tileBrick__fresh__2: "1",
    tileBrick__fresh__3: "2",
    tileBrick__fresh__4: "0",
    tileBrick__weathered__1: "0",
    tileBrick__weathered__2: "1",
    tileBrick__weathered__3: "0",
    tileBrick__weathered__4: "0",
    woodPaper__fresh__1: "1",
    woodPaper__fresh__2: "1",
    woodPaper__fresh__3: "1",
    woodPaper__fresh__4: "1",
    woodPaper__weathered__1: "1",
    woodPaper__weathered__2: "1",
    woodPaper__weathered__3: "1",
    woodPaper__weathered__4: "1"
  },
  ASData: {
    cigaretteButts__fresh__accumulation: "0",
    cigaretteButts__weathered__accumulation: "10",
    fishingLineRope__fresh__accumulation: "0",
    fishingLineRope__weathered__accumulation: "2",
    plasticCups__fresh__accumulation: "2",
    plasticCups__weathered__accumulation: "0",
    plasticStraws__fresh__accumulation: "0",
    plasticStraws__weathered__accumulation: "13",
    filmedPlastic__fresh__accumulation: "2",
    filmedPlastic__weathered__accumulation: "3",
    miscPlastic__fresh__accumulation: "0",
    miscPlastic__weathered__accumulation: "34",
    plasticBottlesCaps__fresh__accumulation: "1",
    plasticBottlesCaps__weathered__accumulation: "0",
    styrofoam__fresh__accumulation: "1",
    styrofoam__weathered__accumulation: "4",
    foodOrganic__fresh__accumulation: "0",
    foodOrganic__weathered__accumulation: "3",
    urethaneFoam__fresh__accumulation: "1",
    urethaneFoam__weathered__accumulation: "3",
    metal__fresh__accumulation: "2",
    metal__weathered__accumulation: "5",
    glass__fresh__accumulation: "0",
    glass__weathered__accumulation: "2",
    cottonCloth__fresh__accumulation: "0",
    cottonCloth__weathered__accumulation: "0",
    aluminumCans__fresh__accumulation: "1",
    aluminumCans__weathered__accumulation: "1",
    hygieneItems__fresh__accumulation: "0",
    hygieneItems__weathered__accumulation: "1",
    tileBrick__fresh__accumulation: "0",
    tileBrick__weathered__accumulation: "3",
    woodPaper__fresh__accumulation: "0",
    woodPaper__weathered__accumulation: "0"        
  },
  displayStrings: {
    usage: {
      com: false,
      other: false,
      rec: true,
      rem: false
    },
    locChoice: {
      debris: true,
      other: false,
      prox: false
    },
    subType: {
      other: false,
      p: false,
      rr: false,
      s: true,
      sea: false
    },
    incompleteSurvey: {
      area: false,
      other: false,
      people: false,
      time: false,
      trash: false
    }
  },
  isInputting: false,
  isReviewing: true,
  isSubmitted: false,
  user: "",
  email: "",
  userID: "",
  invalidForm: false,
  autoFilledBeachData: null
}

// tests remote/unused option of major usage
var testSurveyFormState2 = {
  surveyData: {
    beachID: null,
    beachName: "Boardwalk Beach (test)",
    cleanUpDate: "2020-03-23",
    cleanUpTime: "10:30",
    compassDegrees: "180",
    email: "stgibson@ucsc.edu",
    latDeg: "36",
    latDir: "1",
    latMin: "57",
    latSec: "12",
    locationChoiceDebris: true,
    lonDeg: "122",
    lonDir: "-1",
    lonMin: "2",
    lonSec: "28",
    microFreshTotalRib1: "0",
    microFreshTotalRib2: "0",
    microFreshTotalRib3: "0",
    microFreshTotalRib4: "0",
    microWeatheredTotalRib1: "0",
    microWeatheredTotalRib2: "0",
    microWeatheredTotalRib3: "0",
    microWeatheredTotalRib4: "0",
    orgLoc: "Santa Cruz, United States of America",
    orgName: "Clean Oceans International",
    rib1End: "50",
    rib1Start: "5",
    rib2End: "50",
    rib2Start: "10",
    rib3End: "50",
    rib3Start: "16",
    rib4End: "50",
    rib4Start: "27",
    riverDistance: "10",
    riverName: "Kawa Rivera",
    slope: "winter",
    substrateTypeSand: true,
    tideHeightA: "10",
    tideHeightB: "10",
    tideTimeA: "16:00",
    tideTimeB: "12:00",
    tideTypeA: "high",
    tideTypeB: "low",
    usageRemoteUnused: true,
    userFirst: "Sean",
    userLast: "Gibson",
    windDir: "s",
    windSpeed: "10"
  },
  SRSData: {
    cigaretteButts__fresh__1: "5",
    cigaretteButts__fresh__2: "6",
    cigaretteButts__fresh__3: "4",
    cigaretteButts__fresh__4: "5",
    cigaretteButts__weathered__1: "3",
    cigaretteButts__weathered__2: "0",
    cigaretteButts__weathered__3: "3",
    cigaretteButts__weathered__4: "3",
    fishingLineRope__fresh__1: "1",
    fishingLineRope__fresh__2: "2",
    fishingLineRope__fresh__3: "4",
    fishingLineRope__fresh__4: "3",
    fishingLineRope__weathered__1: "3",
    fishingLineRope__weathered__2: "4",
    fishingLineRope__weathered__3: "0",
    fishingLineRope__weathered__4: "0",
    plasticCups__fresh__1: "2",
    plasticCups__fresh__2: "2",
    plasticCups__fresh__3: "2",
    plasticCups__fresh__4: "2",
    plasticCups__weathered__1: "3",
    plasticCups__weathered__2: "3",
    plasticCups__weathered__3: "3",
    plasticCups__weathered__4: "3",
    plasticStraws__fresh__1: "0",
    plasticStraws__fresh__2: "0",
    plasticStraws__fresh__3: "1",
    plasticStraws__fresh__4: "3",
    plasticStraws__weathered__1: "1",
    plasticStraws__weathered__2: "6",
    plasticStraws__weathered__3: "3",
    plasticStraws__weathered__4: "2",
    filmedPlastic__fresh__1: "0",
    filmedPlastic__fresh__2: "0",
    filmedPlastic__fresh__3: "0",
    filmedPlastic__fresh__4: "0",
    filmedPlastic__weathered__1: "0",
    filmedPlastic__weathered__2: "0",
    filmedPlastic__weathered__3: "0",
    filmedPlastic__weathered__4: "0",
    miscPlastic__fresh__1: "2",
    miscPlastic__fresh__2: "1",
    miscPlastic__fresh__3: "1",
    miscPlastic__fresh__4: "2",
    miscPlastic__weathered__1: "1",
    miscPlastic__weathered__2: "1",
    miscPlastic__weathered__3: "0",
    miscPlastic__weathered__4: "1",
    plasticBottlesCaps__fresh__1: "1",
    plasticBottlesCaps__fresh__2: "1",
    plasticBottlesCaps__fresh__3: "1",
    plasticBottlesCaps__fresh__4: "0",
    plasticBottlesCaps__weathered__1: "2",
    plasticBottlesCaps__weathered__2: "4",
    plasticBottlesCaps__weathered__3: "3",
    plasticBottlesCaps__weathered__4: "1",
    styrofoam__fresh__1: "1",
    styrofoam__fresh__2: "1",
    styrofoam__fresh__3: "0",
    styrofoam__fresh__4: "0",
    styrofoam__weathered__1: "0",
    styrofoam__weathered__2: "0",
    styrofoam__weathered__3: "1",
    styrofoam__weathered__4: "1",
    foodOrganic__fresh__1: "2",
    foodOrganic__fresh__2: "0",
    foodOrganic__fresh__3: "1",
    foodOrganic__fresh__4: "2",
    foodOrganic__weathered__1: "1",
    foodOrganic__weathered__2: "0",
    foodOrganic__weathered__3: "0",
    foodOrganic__weathered__4: "0",
    urethaneFoam__fresh__1: "0",
    urethaneFoam__fresh__2: "0",
    urethaneFoam__fresh__3: "1",
    urethaneFoam__fresh__4: "1",
    urethaneFoam__weathered__1: "1",
    urethaneFoam__weathered__2: "1",
    urethaneFoam__weathered__3: "0",
    urethaneFoam__weathered__4: "0",
    metal__fresh__1: "0",
    metal__fresh__2: "0",
    metal__fresh__3: "0",
    metal__fresh__4: "0",
    metal__weathered__1: "0",
    metal__weathered__2: "0",
    metal__weathered__3: "1",
    metal__weathered__4: "0",
    glass__fresh__1: "1",
    glass__fresh__2: "1",
    glass__fresh__3: "0",
    glass__fresh__4: "0",
    glass__weathered__1: "0",
    glass__weathered__2: "0",
    glass__weathered__3: "0",
    glass__weathered__4: "0",
    cottonCloth__fresh__1: "1",
    cottonCloth__fresh__2: "1",
    cottonCloth__fresh__3: "0",
    cottonCloth__fresh__4: "2",
    cottonCloth__weathered__1: "2",
    cottonCloth__weathered__2: "2",
    cottonCloth__weathered__3: "4",
    cottonCloth__weathered__4: "0",
    aluminumCans__fresh__1: "1",
    aluminumCans__fresh__2: "0",
    aluminumCans__fresh__3: "0",
    aluminumCans__fresh__4: "1",
    aluminumCans__weathered__1: "0",
    aluminumCans__weathered__2: "0",
    aluminumCans__weathered__3: "0",
    aluminumCans__weathered__4: "1",
    hygieneItems__fresh__1: "0",
    hygieneItems__fresh__2: "0",
    hygieneItems__fresh__3: "0",
    hygieneItems__fresh__4: "1",
    hygieneItems__weathered__1: "0",
    hygieneItems__weathered__2: "0",
    hygieneItems__weathered__3: "0",
    hygieneItems__weathered__4: "1",
    tileBrick__fresh__1: "0",
    tileBrick__fresh__2: "1",
    tileBrick__fresh__3: "2",
    tileBrick__fresh__4: "0",
    tileBrick__weathered__1: "0",
    tileBrick__weathered__2: "1",
    tileBrick__weathered__3: "0",
    tileBrick__weathered__4: "0",
    woodPaper__fresh__1: "1",
    woodPaper__fresh__2: "1",
    woodPaper__fresh__3: "1",
    woodPaper__fresh__4: "1",
    woodPaper__weathered__1: "1",
    woodPaper__weathered__2: "1",
    woodPaper__weathered__3: "1",
    woodPaper__weathered__4: "1"
  },
  ASData: {
    cigaretteButts__fresh__accumulation: "0",
    cigaretteButts__weathered__accumulation: "10",
    fishingLineRope__fresh__accumulation: "0",
    fishingLineRope__weathered__accumulation: "2",
    plasticCups__fresh__accumulation: "2",
    plasticCups__weathered__accumulation: "0",
    plasticStraws__fresh__accumulation: "0",
    plasticStraws__weathered__accumulation: "13",
    filmedPlastic__fresh__accumulation: "2",
    filmedPlastic__weathered__accumulation: "3",
    miscPlastic__fresh__accumulation: "0",
    miscPlastic__weathered__accumulation: "34",
    plasticBottlesCaps__fresh__accumulation: "1",
    plasticBottlesCaps__weathered__accumulation: "0",
    styrofoam__fresh__accumulation: "1",
    styrofoam__weathered__accumulation: "4",
    foodOrganic__fresh__accumulation: "0",
    foodOrganic__weathered__accumulation: "3",
    urethaneFoam__fresh__accumulation: "1",
    urethaneFoam__weathered__accumulation: "3",
    metal__fresh__accumulation: "2",
    metal__weathered__accumulation: "5",
    glass__fresh__accumulation: "0",
    glass__weathered__accumulation: "2",
    cottonCloth__fresh__accumulation: "0",
    cottonCloth__weathered__accumulation: "0",
    aluminumCans__fresh__accumulation: "1",
    aluminumCans__weathered__accumulation: "1",
    hygieneItems__fresh__accumulation: "0",
    hygieneItems__weathered__accumulation: "1",
    tileBrick__fresh__accumulation: "0",
    tileBrick__weathered__accumulation: "3",
    woodPaper__fresh__accumulation: "0",
    woodPaper__weathered__accumulation: "0"
  },
  displayStrings: {
    usage: {
      com: false,
      other: false,
      rec: false,
      rem: true
    },
    locChoice: {
      debris: true,
      other: false,
      prox: false
    },
    subType: {
      other: undefined,
      p: false,
      rr: false,
      s: true,
      sea: false
    },
    incompleteSurvey: {
      area: false,
      other: false,
      people: false,
      time: false,
      trash: false
    }
  },
  isInputting: false,
  isReviewing: true,
  isSubmitted: false,
  user: "",
  email: "",
  userID: "",
  invalidForm: false,
  autoFilledBeachData: null
}

// tests comments for wind section
var testSurveyFormState3 = {
  surveyData: {
    beachID: null,
    beachName: "Boardwalk Beach (test)",
    cleanUpDate: "2020-03-23",
    cleanUpTime: "10:30",
    compassDegrees: "180",
    email: "stgibson@ucsc.edu",
    latDeg: "36",
    latDir: "1",
    latMin: "57",
    latSec: "12",
    locationChoiceDebris: true,
    lonDeg: "122",
    lonDir: "-1",
    lonMin: "2",
    lonSec: "28",
    microFreshTotalRib1: "0",
    microFreshTotalRib2: "0",
    microFreshTotalRib3: "0",
    microFreshTotalRib4: "0",
    microWeatheredTotalRib1: "0",
    microWeatheredTotalRib2: "0",
    microWeatheredTotalRib3: "0",
    microWeatheredTotalRib4: "0",
    orgLoc: "Santa Cruz, United States of America",
    orgName: "Clean Oceans International",
    rib1End: "50",
    rib1Start: "5",
    rib2End: "50",
    rib2Start: "10",
    rib3End: "50",
    rib3Start: "16",
    rib4End: "50",
    rib4Start: "27",
    riverDistance: "10",
    riverName: "Kawa Rivera",
    slope: "winter",
    substrateTypeSand: true,
    tideHeightA: "10",
    tideHeightB: "10",
    tideTimeA: "16:00",
    tideTimeB: "12:00",
    tideTypeA: "high",
    tideTypeB: "low",
    usageRecreation: true,
    userFirst: "Sean",
    userLast: "Gibson",
    windComments: "The wind was annoying.",
    windDir: "s",
    windSpeed: "10"
  },
  SRSData: {
    cigaretteButts__fresh__1: "5",
    cigaretteButts__fresh__2: "6",
    cigaretteButts__fresh__3: "4",
    cigaretteButts__fresh__4: "5",
    cigaretteButts__weathered__1: "3",
    cigaretteButts__weathered__2: "0",
    cigaretteButts__weathered__3: "3",
    cigaretteButts__weathered__4: "3",
    fishingLineRope__fresh__1: "1",
    fishingLineRope__fresh__2: "2",
    fishingLineRope__fresh__3: "4",
    fishingLineRope__fresh__4: "3",
    fishingLineRope__weathered__1: "3",
    fishingLineRope__weathered__2: "4",
    fishingLineRope__weathered__3: "0",
    fishingLineRope__weathered__4: "0",
    plasticCups__fresh__1: "2",
    plasticCups__fresh__2: "2",
    plasticCups__fresh__3: "2",
    plasticCups__fresh__4: "2",
    plasticCups__weathered__1: "3",
    plasticCups__weathered__2: "3",
    plasticCups__weathered__3: "3",
    plasticCups__weathered__4: "3",
    plasticStraws__fresh__1: "0",
    plasticStraws__fresh__2: "0",
    plasticStraws__fresh__3: "1",
    plasticStraws__fresh__4: "3",
    plasticStraws__weathered__1: "1",
    plasticStraws__weathered__2: "6",
    plasticStraws__weathered__3: "3",
    plasticStraws__weathered__4: "2",
    filmedPlastic__fresh__1: "0",
    filmedPlastic__fresh__2: "0",
    filmedPlastic__fresh__3: "0",
    filmedPlastic__fresh__4: "0",
    filmedPlastic__weathered__1: "0",
    filmedPlastic__weathered__2: "0",
    filmedPlastic__weathered__3: "0",
    filmedPlastic__weathered__4: "0",
    miscPlastic__fresh__1: "2",
    miscPlastic__fresh__2: "1",
    miscPlastic__fresh__3: "1",
    miscPlastic__fresh__4: "2",
    miscPlastic__weathered__1: "1",
    miscPlastic__weathered__2: "1",
    miscPlastic__weathered__3: "0",
    miscPlastic__weathered__4: "1",
    plasticBottlesCaps__fresh__1: "1",
    plasticBottlesCaps__fresh__2: "1",
    plasticBottlesCaps__fresh__3: "1",
    plasticBottlesCaps__fresh__4: "0",
    plasticBottlesCaps__weathered__1: "2",
    plasticBottlesCaps__weathered__2: "4",
    plasticBottlesCaps__weathered__3: "3",
    plasticBottlesCaps__weathered__4: "1",
    styrofoam__fresh__1: "1",
    styrofoam__fresh__2: "1",
    styrofoam__fresh__3: "0",
    styrofoam__fresh__4: "0",
    styrofoam__weathered__1: "0",
    styrofoam__weathered__2: "0",
    styrofoam__weathered__3: "1",
    styrofoam__weathered__4: "1",
    foodOrganic__fresh__1: "2",
    foodOrganic__fresh__2: "0",
    foodOrganic__fresh__3: "1",
    foodOrganic__fresh__4: "2",
    foodOrganic__weathered__1: "1",
    foodOrganic__weathered__2: "0",
    foodOrganic__weathered__3: "0",
    foodOrganic__weathered__4: "0",
    urethaneFoam__fresh__1: "0",
    urethaneFoam__fresh__2: "0",
    urethaneFoam__fresh__3: "1",
    urethaneFoam__fresh__4: "1",
    urethaneFoam__weathered__1: "1",
    urethaneFoam__weathered__2: "1",
    urethaneFoam__weathered__3: "0",
    urethaneFoam__weathered__4: "0",
    metal__fresh__1: "0",
    metal__fresh__2: "0",
    metal__fresh__3: "0",
    metal__fresh__4: "0",
    metal__weathered__1: "0",
    metal__weathered__2: "0",
    metal__weathered__3: "1",
    metal__weathered__4: "0",
    glass__fresh__1: "1",
    glass__fresh__2: "1",
    glass__fresh__3: "0",
    glass__fresh__4: "0",
    glass__weathered__1: "0",
    glass__weathered__2: "0",
    glass__weathered__3: "0",
    glass__weathered__4: "0",
    cottonCloth__fresh__1: "1",
    cottonCloth__fresh__2: "1",
    cottonCloth__fresh__3: "0",
    cottonCloth__fresh__4: "2",
    cottonCloth__weathered__1: "2",
    cottonCloth__weathered__2: "2",
    cottonCloth__weathered__3: "4",
    cottonCloth__weathered__4: "0",
    aluminumCans__fresh__1: "1",
    aluminumCans__fresh__2: "0",
    aluminumCans__fresh__3: "0",
    aluminumCans__fresh__4: "1",
    aluminumCans__weathered__1: "0",
    aluminumCans__weathered__2: "0",
    aluminumCans__weathered__3: "0",
    aluminumCans__weathered__4: "1",
    hygieneItems__fresh__1: "0",
    hygieneItems__fresh__2: "0",
    hygieneItems__fresh__3: "0",
    hygieneItems__fresh__4: "1",
    hygieneItems__weathered__1: "0",
    hygieneItems__weathered__2: "0",
    hygieneItems__weathered__3: "0",
    hygieneItems__weathered__4: "1",
    tileBrick__fresh__1: "0",
    tileBrick__fresh__2: "1",
    tileBrick__fresh__3: "2",
    tileBrick__fresh__4: "0",
    tileBrick__weathered__1: "0",
    tileBrick__weathered__2: "1",
    tileBrick__weathered__3: "0",
    tileBrick__weathered__4: "0",
    woodPaper__fresh__1: "1",
    woodPaper__fresh__2: "1",
    woodPaper__fresh__3: "1",
    woodPaper__fresh__4: "1",
    woodPaper__weathered__1: "1",
    woodPaper__weathered__2: "1",
    woodPaper__weathered__3: "1",
    woodPaper__weathered__4: "1"
  },
  ASData: {
    cigaretteButts__fresh__accumulation: "0",
    cigaretteButts__weathered__accumulation: "10",
    fishingLineRope__fresh__accumulation: "0",
    fishingLineRope__weathered__accumulation: "2",
    plasticCups__fresh__accumulation: "2",
    plasticCups__weathered__accumulation: "0",
    plasticStraws__fresh__accumulation: "0",
    plasticStraws__weathered__accumulation: "13",
    filmedPlastic__fresh__accumulation: "2",
    filmedPlastic__weathered__accumulation: "3",
    miscPlastic__fresh__accumulation: "0",
    miscPlastic__weathered__accumulation: "34",
    plasticBottlesCaps__fresh__accumulation: "1",
    plasticBottlesCaps__weathered__accumulation: "0",
    styrofoam__fresh__accumulation: "1",
    styrofoam__weathered__accumulation: "4",
    foodOrganic__fresh__accumulation: "0",
    foodOrganic__weathered__accumulation: "3",
    urethaneFoam__fresh__accumulation: "1",
    urethaneFoam__weathered__accumulation: "3",
    metal__fresh__accumulation: "2",
    metal__weathered__accumulation: "5",
    glass__fresh__accumulation: "0",
    glass__weathered__accumulation: "2",
    cottonCloth__fresh__accumulation: "0",
    cottonCloth__weathered__accumulation: "0",
    aluminumCans__fresh__accumulation: "1",
    aluminumCans__weathered__accumulation: "1",
    hygieneItems__fresh__accumulation: "0",
    hygieneItems__weathered__accumulation: "1",
    tileBrick__fresh__accumulation: "0",
    tileBrick__weathered__accumulation: "3",
    woodPaper__fresh__accumulation: "0",
    woodPaper__weathered__accumulation: "0"
  },
  displayStrings: {
    usage: {
      com: false,
      other: false,
      rec: true,
      rem: false
    },
    locChoice: {
      debris: true,
      other: false,
      prox: false
    },
    subType: {
      other: false,
      p: false,
      rr: false,
      s: true,
      sea: false
    },
    incompleteSurvey: {
      area: false,
      other: false,
      people: false,
      time: false,
      trash: false
    }
  },
  isInputting: false,
  isReviewing: true,
  isSubmitted: false,
  user: "",
  email: "",
  userID: "",
  invalidForm: false,
  autoFilledBeachData: null
}

// tests option to check why we did not do an accumulation survey
var testSurveyFormState4 = {
  surveyData: {
    beachID: null,
    beachName: "Boardwalk Beach (test)",
    cleanUpDate: "2020-03-23",
    cleanUpTime: "10:30",
    compassDegrees: "180",
    email: "stgibson@ucsc.edu",
    incompleteSurveyPeople: true,
    latDeg: "36",
    latDir: "1",
    latMin: "57",
    latSec: "12",
    locationChoiceDebris: true,
    lonDeg: "122",
    lonDir: "-1",
    lonMin: "2",
    lonSec: "28",
    microFreshTotalRib1: "0",
    microFreshTotalRib2: "0",
    microFreshTotalRib3: "0",
    microFreshTotalRib4: "0",
    microWeatheredTotalRib1: "0",
    microWeatheredTotalRib2: "0",
    microWeatheredTotalRib3: "0",
    microWeatheredTotalRib4: "0",
    orgLoc: "Santa Cruz, United States of America",
    orgName: "Clean Oceans International",
    rib1End: "50",
    rib1Start: "5",
    rib2End: "50",
    rib2Start: "10",
    rib3End: "50",
    rib3Start: "16",
    rib4End: "50",
    rib4Start: "27",
    riverDistance: "10",
    riverName: "Kawa Rivera",
    slope: "winter",
    substrateTypeSand: true,
    tideHeightA: "10",
    tideHeightB: "10",
    tideTimeA: "16:00",
    tideTimeB: "12:00",
    tideTypeA: "high",
    tideTypeB: "low",
    usageRecreation: true,
    userFirst: "Sean",
    userLast: "Gibson",
    windDir: "s",
    windSpeed: "10"
  },
  SRSData: {
    cigaretteButts__fresh__1: "5",
    cigaretteButts__fresh__2: "6",
    cigaretteButts__fresh__3: "4",
    cigaretteButts__fresh__4: "5",
    cigaretteButts__weathered__1: "3",
    cigaretteButts__weathered__2: "0",
    cigaretteButts__weathered__3: "3",
    cigaretteButts__weathered__4: "3",
    fishingLineRope__fresh__1: "1",
    fishingLineRope__fresh__2: "2",
    fishingLineRope__fresh__3: "4",
    fishingLineRope__fresh__4: "3",
    fishingLineRope__weathered__1: "3",
    fishingLineRope__weathered__2: "4",
    fishingLineRope__weathered__3: "0",
    fishingLineRope__weathered__4: "0",
    plasticCups__fresh__1: "2",
    plasticCups__fresh__2: "2",
    plasticCups__fresh__3: "2",
    plasticCups__fresh__4: "2",
    plasticCups__weathered__1: "3",
    plasticCups__weathered__2: "3",
    plasticCups__weathered__3: "3",
    plasticCups__weathered__4: "3",
    plasticStraws__fresh__1: "0",
    plasticStraws__fresh__2: "0",
    plasticStraws__fresh__3: "1",
    plasticStraws__fresh__4: "3",
    plasticStraws__weathered__1: "1",
    plasticStraws__weathered__2: "6",
    plasticStraws__weathered__3: "3",
    plasticStraws__weathered__4: "2",
    filmedPlastic__fresh__1: "0",
    filmedPlastic__fresh__2: "0",
    filmedPlastic__fresh__3: "0",
    filmedPlastic__fresh__4: "0",
    filmedPlastic__weathered__1: "0",
    filmedPlastic__weathered__2: "0",
    filmedPlastic__weathered__3: "0",
    filmedPlastic__weathered__4: "0",
    miscPlastic__fresh__1: "2",
    miscPlastic__fresh__2: "1",
    miscPlastic__fresh__3: "1",
    miscPlastic__fresh__4: "2",
    miscPlastic__weathered__1: "1",
    miscPlastic__weathered__2: "1",
    miscPlastic__weathered__3: "0",
    miscPlastic__weathered__4: "1",
    plasticBottlesCaps__fresh__1: "1",
    plasticBottlesCaps__fresh__2: "1",
    plasticBottlesCaps__fresh__3: "1",
    plasticBottlesCaps__fresh__4: "0",
    plasticBottlesCaps__weathered__1: "2",
    plasticBottlesCaps__weathered__2: "4",
    plasticBottlesCaps__weathered__3: "3",
    plasticBottlesCaps__weathered__4: "1",
    styrofoam__fresh__1: "1",
    styrofoam__fresh__2: "1",
    styrofoam__fresh__3: "0",
    styrofoam__fresh__4: "0",
    styrofoam__weathered__1: "0",
    styrofoam__weathered__2: "0",
    styrofoam__weathered__3: "1",
    styrofoam__weathered__4: "1",
    foodOrganic__fresh__1: "2",
    foodOrganic__fresh__2: "0",
    foodOrganic__fresh__3: "1",
    foodOrganic__fresh__4: "2",
    foodOrganic__weathered__1: "1",
    foodOrganic__weathered__2: "0",
    foodOrganic__weathered__3: "0",
    foodOrganic__weathered__4: "0",
    urethaneFoam__fresh__1: "0",
    urethaneFoam__fresh__2: "0",
    urethaneFoam__fresh__3: "1",
    urethaneFoam__fresh__4: "1",
    urethaneFoam__weathered__1: "1",
    urethaneFoam__weathered__2: "1",
    urethaneFoam__weathered__3: "0",
    urethaneFoam__weathered__4: "0",
    metal__fresh__1: "0",
    metal__fresh__2: "0",
    metal__fresh__3: "0",
    metal__fresh__4: "0",
    metal__weathered__1: "0",
    metal__weathered__2: "0",
    metal__weathered__3: "1",
    metal__weathered__4: "0",
    glass__fresh__1: "1",
    glass__fresh__2: "1",
    glass__fresh__3: "0",
    glass__fresh__4: "0",
    glass__weathered__1: "0",
    glass__weathered__2: "0",
    glass__weathered__3: "0",
    glass__weathered__4: "0",
    cottonCloth__fresh__1: "1",
    cottonCloth__fresh__2: "1",
    cottonCloth__fresh__3: "0",
    cottonCloth__fresh__4: "2",
    cottonCloth__weathered__1: "2",
    cottonCloth__weathered__2: "2",
    cottonCloth__weathered__3: "4",
    cottonCloth__weathered__4: "0",
    aluminumCans__fresh__1: "1",
    aluminumCans__fresh__2: "0",
    aluminumCans__fresh__3: "0",
    aluminumCans__fresh__4: "1",
    aluminumCans__weathered__1: "0",
    aluminumCans__weathered__2: "0",
    aluminumCans__weathered__3: "0",
    aluminumCans__weathered__4: "1",
    hygieneItems__fresh__1: "0",
    hygieneItems__fresh__2: "0",
    hygieneItems__fresh__3: "0",
    hygieneItems__fresh__4: "1",
    hygieneItems__weathered__1: "0",
    hygieneItems__weathered__2: "0",
    hygieneItems__weathered__3: "0",
    hygieneItems__weathered__4: "1",
    tileBrick__fresh__1: "0",
    tileBrick__fresh__2: "1",
    tileBrick__fresh__3: "2",
    tileBrick__fresh__4: "0",
    tileBrick__weathered__1: "0",
    tileBrick__weathered__2: "1",
    tileBrick__weathered__3: "0",
    tileBrick__weathered__4: "0",
    woodPaper__fresh__1: "1",
    woodPaper__fresh__2: "1",
    woodPaper__fresh__3: "1",
    woodPaper__fresh__4: "1",
    woodPaper__weathered__1: "1",
    woodPaper__weathered__2: "1",
    woodPaper__weathered__3: "1",
    woodPaper__weathered__4: "1"
  },
  ASData: {
  },
  displayStrings: {
    usage: {
      com: false,
      other: false,
      rec: true,
      rem: false
    },
    locChoice: {
      debris: true,
      other: false,
      prox: false
    },
    subType: {
      other: false,
      p: false,
      rr: false,
      s: true,
      sea: false
    },
    incompleteSurvey: {
      area: false,
      other: false,
      people: true,
      time: false,
      trash: false
    }
  },
  isInputting: false,
  isReviewing: true,
  isSubmitted: false,
  user: "",
  email: "",
  userID: "",
  invalidForm: false,
  autoFilledBeachData: null
}

// survey data for testing updateDisplayString(), this tests one option each
var testSurveyFormSurveyData1 = {
  beachID: null,
  beachName: "Boardwalk Beach (test)",
  cleanUpDate: "2020-03-23",
  cleanUpTime: "10:30",
  compassDegrees: "180",
  email: "stgibson@ucsc.edu",
  incompleteSurveyPeople: true,
  latDeg: "36",
  latDir: "1",
  latMin: "57",
  latSec: "12",
  locationChoiceDebris: true,
  lonDeg: "122",
  lonDir: "-1",
  lonMin: "2",
  lonSec: "28",
  microFreshTotalRib1: "0",
  microFreshTotalRib2: "0",
  microFreshTotalRib3: "0",
  microFreshTotalRib4: "0",
  microWeatheredTotalRib1: "0",
  microWeatheredTotalRib2: "0",
  microWeatheredTotalRib3: "0",
  microWeatheredTotalRib4: "0",
  orgLoc: "Santa Cruz, United States of America",
  orgName: "Clean Oceans International",
  rib1End: "50",
  rib1Start: "5",
  rib2End: "50",
  rib2Start: "10",
  rib3End: "50",
  rib3Start: "16",
  rib4End: "50",
  rib4Start: "27",
  riverDistance: "10",
  riverName: "Kawa Rivera",
  slope: "winter",
  substrateTypeSand: true,
  tideHeightA: "10",
  tideHeightB: "10",
  tideTimeA: "16:00",
  tideTimeB: "12:00",
  tideTypeA: "high",
  tideTypeB: "low",
  usageRecreation: true,
  userFirst: "Sean",
  userLast: "Gibson",
  windDir: "s",
  windSpeed: "10"
}

// expected output for testing updateDisplayString() using above as surveyData
var updateDisplayStringExpected1 = {
  usage: "Recreation",
  locChoice: "Known for Debris",
  subType: "Sand",
  incompleteSurvey: "Not enough people"
}

// two options selected for each
var testSurveyFormSurveyData2 = {
  beachID: null,
  beachName: "Boardwalk Beach (test)",
  cleanUpDate: "2020-03-23",
  cleanUpTime: "10:30",
  compassDegrees: "180",
  email: "stgibson@ucsc.edu",
  incompleteSurveyPeople: true,
  incompleteSurveyTime: true,
  latDeg: "36",
  latDir: "1",
  latMin: "57",
  latSec: "12",
  locationChoiceDebris: true,
  locationChoiceProximity: true,
  lonDeg: "122",
  lonDir: "-1",
  lonMin: "2",
  lonSec: "28",
  microFreshTotalRib1: "0",
  microFreshTotalRib2: "0",
  microFreshTotalRib3: "0",
  microFreshTotalRib4: "0",
  microWeatheredTotalRib1: "0",
  microWeatheredTotalRib2: "0",
  microWeatheredTotalRib3: "0",
  microWeatheredTotalRib4: "0",
  orgLoc: "Santa Cruz, United States of America",
  orgName: "Clean Oceans International",
  rib1End: "50",
  rib1Start: "5",
  rib2End: "50",
  rib2Start: "10",
  rib3End: "50",
  rib3Start: "16",
  rib4End: "50",
  rib4Start: "27",
  riverDistance: "10",
  riverName: "Kawa Rivera",
  slope: "winter",
  substrateTypeSand: true,
  substrateTypeRipRap: true,
  tideHeightA: "10",
  tideHeightB: "10",
  tideTimeA: "16:00",
  tideTimeB: "12:00",
  tideTypeA: "high",
  tideTypeB: "low",
  usageRecreation: true,
  usageCommercial: true,
  userFirst: "Sean",
  userLast: "Gibson",
  windDir: "s",
  windSpeed: "10"
}

// expected output for testing updateDisplayString() using above as surveyData
var updateDisplayStringExpected2 = {
  usage: "Recreation, Commercial",
  locChoice: "Proximity/Convenience, Known for Debris",
  subType: "Sand, Rip Rap",
  incompleteSurvey: "Not enough time, Not enough people"
}

// other selected for each
var testSurveyFormSurveyData3 = {
  beachID: null,
  beachName: "Boardwalk Beach (test)",
  cleanUpDate: "2020-03-23",
  cleanUpTime: "10:30",
  compassDegrees: "180",
  email: "stgibson@ucsc.edu",
  incompleteSurveyOther: "Storm",
  latDeg: "36",
  latDir: "1",
  latMin: "57",
  latSec: "12",
  locationChoiceOther: "Beautiful place",
  lonDeg: "122",
  lonDir: "-1",
  lonMin: "2",
  lonSec: "28",
  microFreshTotalRib1: "0",
  microFreshTotalRib2: "0",
  microFreshTotalRib3: "0",
  microFreshTotalRib4: "0",
  microWeatheredTotalRib1: "0",
  microWeatheredTotalRib2: "0",
  microWeatheredTotalRib3: "0",
  microWeatheredTotalRib4: "0",
  orgLoc: "Santa Cruz, United States of America",
  orgName: "Clean Oceans International",
  rib1End: "50",
  rib1Start: "5",
  rib2End: "50",
  rib2Start: "10",
  rib3End: "50",
  rib3Start: "16",
  rib4End: "50",
  rib4Start: "27",
  riverDistance: "10",
  riverName: "Kawa Rivera",
  slope: "winter",
  substrateTypeOther: "Dirt",
  tideHeightA: "10",
  tideHeightB: "10",
  tideTimeA: "16:00",
  tideTimeB: "12:00",
  tideTypeA: "high",
  tideTypeB: "low",
  usageOther: "Military",
  userFirst: "Sean",
  userLast: "Gibson",
  windDir: "s",
  windSpeed: "10"
}

// expected output for testing updateDisplayString() using above as surveyData
var updateDisplayStringExpected3 = {
  usage: "Military",
  locChoice: "Beautiful place",
  subType: "Dirt",
  incompleteSurvey: "Storm"
}

// one option and other selected for each
var testSurveyFormSurveyData4 = {
  beachID: null,
  beachName: "Boardwalk Beach (test)",
  cleanUpDate: "2020-03-23",
  cleanUpTime: "10:30",
  compassDegrees: "180",
  email: "stgibson@ucsc.edu",
  incompleteSurveyOther: "Storm",
  incompleteSurveyPeople: true,
  latDeg: "36",
  latDir: "1",
  latMin: "57",
  latSec: "12",
  locationChoiceDebris: true,
  locationChoiceOther: "Beautiful place",
  lonDeg: "122",
  lonDir: "-1",
  lonMin: "2",
  lonSec: "28",
  microFreshTotalRib1: "0",
  microFreshTotalRib2: "0",
  microFreshTotalRib3: "0",
  microFreshTotalRib4: "0",
  microWeatheredTotalRib1: "0",
  microWeatheredTotalRib2: "0",
  microWeatheredTotalRib3: "0",
  microWeatheredTotalRib4: "0",
  orgLoc: "Santa Cruz, United States of America",
  orgName: "Clean Oceans International",
  rib1End: "50",
  rib1Start: "5",
  rib2End: "50",
  rib2Start: "10",
  rib3End: "50",
  rib3Start: "16",
  rib4End: "50",
  rib4Start: "27",
  riverDistance: "10",
  riverName: "Kawa Rivera",
  slope: "winter",
  substrateTypeOther: "Dirt",
  substrateTypeSand: true,
  tideHeightA: "10",
  tideHeightB: "10",
  tideTimeA: "16:00",
  tideTimeB: "12:00",
  tideTypeA: "high",
  tideTypeB: "low",
  usageOther: "Military",
  usageRecreation: true,
  userFirst: "Sean",
  userLast: "Gibson",
  windDir: "s",
  windSpeed: "10"
}

// expected output for testing updateDisplayString() using above as surveyData
var updateDisplayStringExpected4 = {
  usage: "Recreation, Military",
  locChoice: "Known for Debris, Beautiful place",
  subType: "Sand, Dirt",
  incompleteSurvey: "Not enough people, Storm"
}

// all options, including other, selected for each
var testSurveyFormSurveyData5 = {
  beachID: null,
  beachName: "Boardwalk Beach (test)",
  cleanUpDate: "2020-03-23",
  cleanUpTime: "10:30",
  compassDegrees: "180",
  email: "stgibson@ucsc.edu",
  incompleteSurveyArea: true,
  incompleteSurveyOther: "Storm",
  incompleteSurveyPeople: true,
  incompleteSurveyTime: true,
  incompleteSurveyTrash: true,
  latDeg: "36",
  latDir: "1",
  latMin: "57",
  latSec: "12",
  locationChoiceDebris: true,
  locationChoiceProximity: true,
  locationChoiceOther: "Beautiful place",
  lonDeg: "122",
  lonDir: "-1",
  lonMin: "2",
  lonSec: "28",
  microFreshTotalRib1: "0",
  microFreshTotalRib2: "0",
  microFreshTotalRib3: "0",
  microFreshTotalRib4: "0",
  microWeatheredTotalRib1: "0",
  microWeatheredTotalRib2: "0",
  microWeatheredTotalRib3: "0",
  microWeatheredTotalRib4: "0",
  orgLoc: "Santa Cruz, United States of America",
  orgName: "Clean Oceans International",
  rib1End: "50",
  rib1Start: "5",
  rib2End: "50",
  rib2Start: "10",
  rib3End: "50",
  rib3Start: "16",
  rib4End: "50",
  rib4Start: "27",
  riverDistance: "10",
  riverName: "Kawa Rivera",
  slope: "winter",
  substrateTypeOther: "Dirt",
  substrateTypePebble: true,
  substrateTypeRipRap: true,
  substrateTypeSand: true,
  substrateTypeSeaweed: true,
  tideHeightA: "10",
  tideHeightB: "10",
  tideTimeA: "16:00",
  tideTimeB: "12:00",
  tideTypeA: "high",
  tideTypeB: "low",
  usageCommercial: true,
  usageOther: "Military",
  usageRecreation: true,
  usageRemoteUnused: true,
  userFirst: "Sean",
  userLast: "Gibson",
  windDir: "s",
  windSpeed: "10"
}

// expected output for testing updateDisplayString() using above as surveyData
var updateDisplayStringExpected5 = {
  usage: "Recreation, Commercial, Remote/Unused, Military",
  locChoice: "Proximity/Convenience, Known for Debris, Beautiful place",
  subType: "Sand, Pebble, Rip Rap, Seaweed, Dirt",
  incompleteSurvey:
    "Not enough time, Not enough people, Too much area, Too much trash, Storm"
}

// incomplete survey options not selected
var testSurveyFormSurveyData6 = {
  beachID: null,
  beachName: "Boardwalk Beach (test)",
  cleanUpDate: "2020-03-23",
  cleanUpTime: "10:30",
  compassDegrees: "180",
  email: "stgibson@ucsc.edu",
  latDeg: "36",
  latDir: "1",
  latMin: "57",
  latSec: "12",
  locationChoiceDebris: true,
  lonDeg: "122",
  lonDir: "-1",
  lonMin: "2",
  lonSec: "28",
  microFreshTotalRib1: "0",
  microFreshTotalRib2: "0",
  microFreshTotalRib3: "0",
  microFreshTotalRib4: "0",
  microWeatheredTotalRib1: "0",
  microWeatheredTotalRib2: "0",
  microWeatheredTotalRib3: "0",
  microWeatheredTotalRib4: "0",
  orgLoc: "Santa Cruz, United States of America",
  orgName: "Clean Oceans International",
  rib1End: "50",
  rib1Start: "5",
  rib2End: "50",
  rib2Start: "10",
  rib3End: "50",
  rib3Start: "16",
  rib4End: "50",
  rib4Start: "27",
  riverDistance: "10",
  riverName: "Kawa Rivera",
  slope: "winter",
  substrateTypeSand: true,
  tideHeightA: "10",
  tideHeightB: "10",
  tideTimeA: "16:00",
  tideTimeB: "12:00",
  tideTypeA: "high",
  tideTypeB: "low",
  usageRecreation: true,
  userFirst: "Sean",
  userLast: "Gibson",
  windDir: "s",
  windSpeed: "10"
}

// expected output for testing updateDisplayString() using above as surveyData
var updateDisplayStringExpected6 = {
  usage: "Recreation",
  locChoice: "Known for Debris",
  subType: "Sand",
  incompleteSurvey: ""
}

export {
  testSurveyFormState1,
  testSurveyFormState2,
  testSurveyFormState3,
  testSurveyFormState4,
  testSurveyFormSurveyData1,
  testSurveyFormSurveyData2,
  testSurveyFormSurveyData3,
  testSurveyFormSurveyData4,
  testSurveyFormSurveyData5,
  testSurveyFormSurveyData6,
  updateDisplayStringExpected1,
  updateDisplayStringExpected2,
  updateDisplayStringExpected3,
  updateDisplayStringExpected4,
  updateDisplayStringExpected5,
  updateDisplayStringExpected6
};